Repository NifTK/NiftyNet, pull requests merged in 2019-06, with the labels that each got.

#356 Adding fix for nifti boolean array convert
  niftynet/io/image_loader.py
  tests/image_loader_test.py
Labels: enhancement

#368 Improve config docs
  doc/source/config_spec.md
  doc/source/filename_matching.md
  doc/source/window_sizes.rst
Labels: documentation, enhancement, work in progress

#374 tested code for classification and segmentation applications
  niftynet/application/classification_application.py
  niftynet/application/segmentation_application.py
  niftynet/layer/layer_util.py
Labels: work in progress

#372 Regression app amendment for output identity resizing
  niftynet/application/regression_application.py
  niftynet/engine/windows_aggregator_identity.py
  niftynet/utilities/user_parameters_default.py
Labels: work in progress

#370 Config file buffer queue documentation
  doc/source/buffer_queue.md
Labels: work in progress

#397 implements no-new net, a better 3d unet
  niftynet/engine/application_factory.py
  niftynet/network/no_new_net.py
Labels: work in progress
